//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellOnConsultingServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExcellOnServiceEntities : DbContext
    {
        public ExcellOnServiceEntities()
            : base("name=ExcellOnServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<HrManagement> HrManagements { get; set; }
        public virtual DbSet<InboundService> InboundServices { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<OutboundService> OutboundServices { get; set; }
        public virtual DbSet<ProductService> ProductServices { get; set; }
        public virtual DbSet<TeleMarketingService> TeleMarketingServices { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
    }
}
