//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellOnConsultingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundService
    {
        public int OutboundID { get; set; }
        public string ServiceName { get; set; }
        public string Cnic { get; set; }
        public string City { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string ServiceType { get; set; }
        public string UserExperience { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
