//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellOnConsultingServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductService
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string ServiceType { get; set; }
        public string Descriptions { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
